name: Keep Render Server Alive

on:
  schedule:
    # Runs every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch:  # allows manual trigger too

jobs:
  ping-render:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render /health
        run: |
          echo "Pinging Render server..."
          curl -s -o /dev/null -w "%{http_code}\n" https://tds-project1-e3v6.onrender.com/health
